-- Criar tabela de notícias no Supabase
DROP TABLE IF EXISTS noticias;

CREATE TABLE noticias (
  id SERIAL PRIMARY KEY,
  titulo TEXT NOT NULL,
  resumo TEXT NOT NULL,
  conteudo TEXT NOT NULL,
  categoria TEXT NOT NULL,
  data DATE NOT NULL,
  autor TEXT NOT NULL,
  imagem TEXT,
  campus TEXT,
  status TEXT NOT NULL DEFAULT 'rascunho' CHECK (status IN ('rascunho', 'pendente', 'aprovado', 'rejeitado'))
);

-- Inserir dados de exemplo (já aprovados)
INSERT INTO noticias (titulo, resumo, conteudo, categoria, data, autor, imagem, campus, status) VALUES
('UFC é destaque em ranking internacional de sustentabilidade', 'A Universidade Federal do Ceará (UFC) alcançou uma posição de destaque no UI GreenMetric World University Ranking 2024, que avalia as práticas de sustentabilidade em instituições de ensino superior em todo o mundo.', 'A Universidade Federal do Ceará (UFC) alcançou uma posição de destaque no UI GreenMetric World University Ranking 2024, que avalia as práticas de sustentabilidade em instituições de ensino superior em todo o mundo. A UFC ficou entre as 5 melhores universidades brasileiras e a primeira do Nordeste, refletindo os esforços contínuos em gestão ambiental, educação para a sustentabilidade e infraestrutura verde. A avaliação considera indicadores como ''Setting and Infrastructure'', ''Energy and Climate Change'', ''Waste'', ''Water'', ''Transportation'' e ''Education and Research''. O resultado é fruto de um trabalho coletivo envolvendo a administração superior, servidores, estudantes e a comunidade em geral, que têm se engajado em projetos como a coleta seletiva, o uso de energias renováveis e a promoção de eventos sobre consciência ambiental.', 'Institucional', '2025-10-22', 'Coordenadoria de Comunicação', '/assets/imagem2.png', 'Pici', 'aprovado'),
('Nova pesquisa sobre Zika Vírus é desenvolvida no Campus do Porangabuçu', 'Pesquisadores da Faculdade de Medicina (FAMED) da UFC publicaram um novo estudo na revista Nature sobre os efeitos neurológicos do Zika Vírus em adultos, uma área até então pouco explorada.', 'Uma equipe de pesquisadores da Faculdade de Medicina (FAMED) da UFC, localizada no Campus do Porangabuçu, publicou um estudo inovador na prestigiada revista Nature. A pesquisa foca nos efeitos neurológicos do Zika Vírus em adultos, revelando que a infecção pode causar complicações a longo prazo, como a síndrome de Guillain-Barré e outras neuropatias, de forma mais frequente do que se imaginava. O estudo acompanhou 200 pacientes adultos que contraíram o vírus durante o surto de 2015 e 2016, utilizando ressonância magnética e análises do líquido cefalorraquidiano para mapear as alterações no sistema nervoso. As descobertas reforçam a necessidade de acompanhamento médico contínuo para pacientes que tiveram a doença.', 'Pesquisa', '2025-11-05', 'Mariana Costa', '/assets/imagem.png', 'Porangabuçu', 'aprovado'),
('Festival de Cultura e Arte acontece no Campus do Benfica', 'O tradicional Festival de Cultura e Arte da UFC tomará conta do Campus do Benfica entre os dias 10 e 15 de novembro, com uma programação gratuita e aberta ao público.', 'Entre os dias 10 e 15 de novembro, o Campus do Benfica será palco do tradicional Festival de Cultura e Arte da UFC. O evento, que chega à sua 20ª edição, contará com uma vasta programação gratuita, incluindo shows musicais, peças de teatro, exposições de artes visuais, oficinas e debates. A abertura oficial acontecerá na Concha Acústica da Reitoria, com a apresentação da Orquestra Sinfônica da UFC. Nomes como Luedji Luna e Zeca Baleiro estão confirmados na programação musical. O festival busca promover a integração entre a comunidade acadêmica e a sociedade, celebrando a diversidade cultural e o talento dos artistas locais e nacionais.', 'Eventos', '2025-11-01', 'Lucas Martins', '/assets/imagem1.jpg', 'Benfica', 'aprovado'),
('Campus de Russas abre inscrições para especialização em Engenharia de Software', 'A especialização é gratuita e voltada para profissionais que desejam aprofundar seus conhecimentos em desenvolvimento de software e novas tecnologias.', 'O Campus da UFC em Russas está com inscrições abertas para a nova turma de sua especialização em Engenharia de Software. O curso é gratuito e tem como público-alvo graduados em Ciência da Computação, Engenharia de Computação, Sistemas de Informação e áreas afins. Com duração de 18 meses, a pós-graduação abordará temas como arquitetura de software, inteligência artificial, desenvolvimento ágil e segurança da informação. As aulas serão ministradas por professores doutores do campus e por profissionais renomados do mercado. As inscrições podem ser feitas on-line até o dia 30 de novembro.', 'Avisos', '2025-10-28', 'Secretaria Acadêmica de Russas', '/assets/imagem3.png', 'Russas', 'aprovado'),
('Projeto de extensão em Quixadá leva robótica para escolas públicas', 'Alunos do curso de Engenharia de Computação do Campus da UFC em Quixadá estão promovendo oficinas de robótica para estudantes do ensino fundamental da região.', 'Um projeto de extensão coordenado por professores e executado por alunos do curso de Engenharia de Computação do Campus da UFC em Quixadá está transformando a realidade de escolas públicas no sertão central cearense. O projeto ''Robótica para Todos'' oferece oficinas semanais de programação e montagem de robôs para estudantes do 6º ao 9º ano. Utilizando kits de baixo custo e software livre, a iniciativa busca despertar o interesse dos jovens pela ciência e tecnologia, além de desenvolver o raciocínio lógico e o trabalho em equipe. O projeto já atendeu mais de 100 alunos e planeja expandir para outras cidades da região no próximo ano.', 'Extensão', '2025-09-15', 'Ana Clara Souza', '/assets/imagem4.jpeg', 'Quixadá', 'aprovado'),
('UFC Crateús inaugura novo bloco de laboratórios de química e física', 'A nova estrutura beneficiará os cursos de graduação em Ciência da Computação e Sistemas de Informação, além de projetos de pesquisa.', 'O Campus da UFC em Crateús inaugurou nesta semana um novo bloco de laboratórios didáticos. A estrutura conta com modernos laboratórios de Química e Física, equipados com instrumentos de última geração para aulas práticas e desenvolvimento de pesquisas. O investimento, de cerca de R$ 2 milhões, visa aprimorar a formação dos estudantes dos cursos de Ciência da Computação e Sistemas de Informação, que possuem disciplinas básicas nessas áreas. A Reitora da UFC, presente na cerimônia, destacou a importância do investimento para a consolidação do campus e para o desenvolvimento científico e tecnológico da região.', 'Institucional', '2025-08-20', 'UFC Informa', '/assets/imagem5.png', 'Crateús', 'aprovado'),
('UFC lança nova versão do Guia de Fontes para imprensa', 'Ferramenta on-line visa auxiliar profissionais de imprensa na busca por fontes qualificadas na universidade.', 'A Coordenadoria de Comunicação e Marketing (UFC Informa) da Universidade Federal do Ceará lançou, nesta quinta-feira (8), a nova versão do Guia de Fontes. Trata-se de uma ferramenta on-line cujo objetivo é auxiliar profissionais de imprensa na busca por fontes qualificadas de informação...', 'Institucional', '2025-12-08', 'UFC Informa', '/assets/imagem6.png', 'Benfica', 'aprovado');

-- Exemplos de notícias pendentes de aprovação
INSERT INTO noticias (titulo, resumo, conteudo, categoria, data, autor, imagem, campus, status) VALUES
('Novo curso de pós-graduação em Inteligência Artificial', 'A UFC está oferecendo um novo programa de mestrado em Inteligência Artificial com foco em aplicações práticas.', 'A Universidade Federal do Ceará inaugurou um novo programa de pós-graduação lato sensu em Inteligência Artificial. O curso tem duração de 18 meses e é voltado para profissionais da área de tecnologia da informação. Serão abordados temas como machine learning, deep learning, processamento de linguagem natural e visão computacional. As aulas serão ministradas por professores doutores e pesquisadores renomados da instituição.', 'Pesquisa', '2025-12-10', 'Prof. Dr. João Silva', '/assets/imagem7.png', 'Pici', 'pendente'),
('Equipe de estudantes vence competição nacional de robótica', 'Alunos do curso de Engenharia Mecânica conquistaram o primeiro lugar na RoboCup Brasileira.', 'Uma equipe formada por estudantes do curso de Engenharia Mecânica da UFC conquistou o primeiro lugar na categoria de resgate da RoboCup Brasileira 2025. A competição aconteceu em São Paulo e reuniu equipes de todo o país. O projeto desenvolvido pelos alunos inclui um robô autônomo capaz de navegar em ambientes complexos e realizar tarefas de resgate simuladas. Esta é a terceira vitória consecutiva da UFC nesta competição.', 'Extensão', '2025-12-09', 'Equipe RoboUFC', '/assets/imagem8.png', 'Pici', 'pendente'),
('Campus de Sobral recebe investimento de R$ 5 milhões', 'Recursos serão destinados à construção de novos laboratórios e modernização da infraestrutura.', 'O Campus da UFC em Sobral recebeu um investimento de R$ 5 milhões do Ministério da Educação para a construção de novos laboratórios de pesquisa e modernização da infraestrutura existente. Os recursos serão utilizados para a criação de um laboratório de biotecnologia e ampliação do espaço para atividades de extensão. A expectativa é que as obras sejam concluídas até o final do próximo ano.', 'Institucional', '2025-12-07', 'Reitoria UFC', '/assets/imagem9.png', 'Sobral', 'pendente');